version: 0.2

env:
  variables:
    PROJECT: DSWebApp
    DOTNET_FRAMEWORK: 4.6.1
phases:
  build:
    commands:
      - nuget restore DSWebApp.sln
      - msbuild DSWebApp.sln /p:Configuration=release /P:deployonbuild=true /p:Platform="any cpu" /p:DebugType=None /p:OutDir=C:\codebuild\artifacts\
      
artifacts:
  files:
    - '**/*'
  base-directory: 'C:\codebuild\artifacts\'

