version: 0.2

env:
  variables:
    PROJECT: DSWebApp
    DOTNET_FRAMEWORK: 4.6.1
phases:
  build:
    commands:
      - nuget restore DSWebApp.sln
      - msbuild DSWebApp.sln /p:Configuration=release /P:deployonbuild=true /p:Platform="any cpu" /p:DebugType=None
      
artifacts:
  files:
    - '**/*'
  base-directory: '.\bin\Release\netcoreapp3.1\Publish'

